version: "3.9"

services:
  frontend:
    build:
      context: ./frontend/send-blue-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite dev server port
    volumes:
      - ./frontend/send-blue-ui:/app
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend  # If your frontend calls an API

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://myuser:mypass@db:5432/mydb
      QUEUE_INTERVAL: 180 # Interval in seconds between sending messages from the queue
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  
  gateway:
    build: ./gateway
    ports:
      - "50051:50051"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data: